name: ci

on: [push]

env:
  FOUNDRY_PROFILE: ci

jobs:
  test:
    strategy:
      fail-fast: true
    name: Run Unix Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build
        continue-on-error: true

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test

  script:
    strategy:
      fail-fast: true
    name: Run Unix Scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build
        continue-on-error: true

      - name: Run scripts
        run: |
          ls -lsa
          ls script/
          for file in script/*; do
            forge script $file
          done